<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta property="vk:app_id" content="<?php echo $this->vkData->id; ?>" />
    <title>Facebook</title>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headLink(); ?>
</head>
<body data-base-prefix="<?php echo $this->baseUrl(); ?>">
<div id="layout">
<div id="header">
    <div id="vk_like_container">
        <div id="vk_like"></div>
    </div>
    <script type="text/javascript">
    VK.Widgets.Like("vk_like", {type: "button", height: 20}, 1);
    </script>
</div>
<?php echo $this->layout()->content ?>
</div>
</body>
</html>